### PR TITLE
README: add Nix / NixOS installation instructions

### PR DESCRIPTION
**Pull request by Icy-Thought**
The `README` as of now lacks the necessary instructions to install Jinx properly on a Nix-based system. Therefore I thought it was worth contributing a simple change to the `README` where I provide the necessary information for Nix users to properly install Jinx.

Otherwise, I appreciate all the effort being put on this amazing project!! :blush:

### CODE REVIEW

**Comment by raxod502** [comment]
For posterity: this is just a mirror, upstream report is at https://github.com/minad/jinx/pull/49/files

**Comment by Icy-Thought** [comment]
For some odd reason the fork pointed to this repository and after noticing it I migrated the issue to the official one.

Appreciate it though!

**Comment by raxod502** [comment]
The fork as in your clone from `straight.el`? Yeah, that's because the author of this package does not publish on MELPA, only on GNU ELPA, which makes it impossible for `straight.el` to identify the upstream package location and forces it to fall back to this mirror (one is generated for every GNU ELPA package, because the GNU ELPA build system is essentially unworkable to run locally).

**Comment by Icy-Thought** [comment]
Oh, that makes sense! Thank you for explaining the situation to me! :)

**Pull request closed without merging**
